server {
    # Escucha en el puerto 443
    listen 443 ssl;
	listen [::]:443 ssl

	# nombre del dominio
	server_name patquesa.42.fr;

	# Las rutas a los certificados obligatorios que genera tu Dockerfile
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

	# Los únicos protocolos de seguridad permitidos por el Subject
    ssl_protocols TLSv1.2 TLSv1.3;
    
    # La carpeta raíz donde están los archivos de WordPress
    root /var/www/html;
    # Los archivos que buscará por defecto al entrar a la web
    index index.php index.html;

    # Qué hacer con las peticiones normales (imágenes, texto, carpetas)
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # Qué hacer cuando detecta un archivo .php (¡La conexión!)
    location ~ \.php$ {
		# Incluye la configuracion estandar de FastCGI de Nginx
        include snippets/fastcgi-php.conf;
        # Le pasa la petición al contenedor de WordPress en el puerto 9000
        fastcgi_pass wordpress:9000; 
    }
}