server {
    # 1. Escucha en el puerto 80 (tráfico web normal)
    listen 80;
    
    # 2. La carpeta raíz donde están los archivos de WordPress
    root /var/www/html;
    
    # 3. Los archivos que buscará por defecto al entrar a la web
    index index.php index.html;

    # 4. Qué hacer con las peticiones normales (imágenes, texto, carpetas)
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # 5. Qué hacer cuando detecta un archivo .php (¡La conexión!)
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        
        # Le pasa la petición al contenedor de WordPress en el puerto 9000
        fastcgi_pass wordpress:9000; 
    }
}